version: '3.8'

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: vessel/app
    ports:
      - ${APP_PORT}:80
    environment:
      CONTAINER_ENV: ${APP_ENV}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG:-client_host=10.0.0.2}
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      WWWUSER: ${WWWUSER}
    volumes:
      - .:/app
    networks:
      - vessel

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        uid: ${WWWUSER}
    image: vessel/node
    user: node
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - vessel

  pgsql:
    image: postgres:12.8
    ports:
      - ${PGSQL_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - vesselpgsql:/var/lib/postgresql/data
    networks:
      - vessel

networks:
  vessel:
    driver: bridge

volumes:
  vesselpgsql:
    driver: local
