name: Docker Image CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run PHPCodeSniffer using cytopia/phpcs Docker image
        run: docker run --rm -v $(pwd):/data cytopia/phpcs --error-severity=1 --warning-severity=8 .
